use_frameworks!

platform :ios, '8.0'

target 'SLModelSqliteObjCKit_Example' do
  pod 'SLModelSqliteObjCKit', :path => '../'

  target 'SLModelSqliteObjCKit_Tests' do
    inherit! :search_paths

    
  end
end
